export const INCREMENT_BUTTON_CLICKED = 'INCREMENT_BUTTON_CLICKED';
export const DECREMENT_BUTTON_CLICKED = 'DECREMENT_BUTTON_CLICKED';
export const FETCH_CRYPTOS_REQUEST = 'FETCH_CRYPTOS_REQUEST';
export const FETCH_CRYPTOS_SUCCESS = 'FETCH_CRYPTOS_SUCCESS';
export const FETCH_CRYPTOS_FAILURE = 'FETCH_CRYPTOS_FAILURE';
export const SORT_BUTTON_CLICKED = 'SORT_BUTTON_CLICKED';
export const FETCH_CRYPTO_BUTTON_CLICKED = 'FETCH_CRYPTO_BUTTON_CLICKED';