export const INCREMENT_BUTTON_CLICKED = 'INCREMENT_BUTTON_CLICKED';
export const DECREMENT_BUTTON_CLICKED = 'DECREMENT_BUTTON_CLICKED';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_REQUEST';